## Universidad Autonoma de Aguascalientes
## Departamento: Ciencias de la Computación
## Carrera: Ingnieria en Computación Inteligente
## Curso: Machine y Deep Learning (McCulloch Pitts)
## Maestro: Dr. Francisco Javier Luna Rosas
## Alumno: Enrique Vélez Durán
## Semestre: Enero_Junio del 2025
### PRÁTICA No. 5 Un pereceptrón es un tipo de modelo de red neuronal muy simple, utilizado principalmnete para problemas de clasificación binaria. Fue desarrollado en 1058 por Frank Roseblatt y es considerado uno de los primeros algoritmos de aprendizaaje supervisado.
### Un perceptrón toma un conjkunto de entradas, las procesa mediante una serie de operaciones matemáticas y produce una salida que puede ser 0 o 1, dependiendo si el resultado final supera un umbral prederterminado

### EJEMPLO: Determinar si se le aprueba una tarjeta de credito a un cliente, considerando la edad y el ahorro que tiene en su cuenta bancaria

In [121]:
import numpy as np 
# import matplotlib.pyplot

In [122]:
personas = np.array([[0.3,0.4], [0.4,0.3],
                  [0.3,0.2], [0.4,0.1],
                  [0.5,0.4], [0.4,0.8],
                  [0.6,0.8], [0.5,0.6],
                  [0.7,0.6], [0.8,0.5]])

In [123]:
clases = np.array([0,0,0,0,0,1,1,1,1,1])

In [124]:
def activacion(pesos, x, b):
    z = pesos * x
    if z.sum() + b > 0:
        return 1
    else:
        return 0

In [125]:
pesos = np.random.uniform(-1,1, size=2)
b = np.random.uniform(-1,1)
pesos, b, activacion(pesos,[0.3, 0.2], b)

(array([0.85368107, 0.96908798]), -0.30286038940765203, 1)

In [126]:
pesos = np.random.uniform(-1,1, size=2)
b = np.random.uniform(-1,1)
tasa_de_aprendizaje = 0.01
epocas = 100

for epoca in range(epocas):
    error_total = 0
    for i in range(len(personas)):
        prediccion = activacion(pesos, personas[i], b)
        error = clases[i] - prediccion
        error_total  += error**2
        pesos[0] += tasa_de_aprendizaje * personas[i][0] * error
        pesos[1] += tasa_de_aprendizaje * personas[i][1] * error
        b += tasa_de_aprendizaje * error
    print(error_total, end=" ")

6 7 7 7 9 9 9 7 7 7 6 7 6 7 7 6 7 6 7 6 7 7 6 7 6 7 7 5 6 5 4 5 4 3 4 4 3 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [127]:
pesos, b, activacion(pesos,[0.3, 0.4], b)

(array([0.20193975, 0.05290637]), np.float64(-0.12277967973373599), 0)

In [128]:
pesos, b, activacion(pesos, [0.8,0.5], b)

(array([0.20193975, 0.05290637]), np.float64(-0.12277967973373599), 1)